<a href="https://colab.research.google.com/github/Daksh-Raghuvanshi/Machine-Learnig-Projects/blob/Before-Final-Commit/Missing_value_imputations_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imputaions using strategies like, -

> SimpleImputer


> Pipeline


> CaolumnTransformer

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')

In [ ]:
print(train.shape)
print(test.shape)

(1460, 81)
(1459, 80)

In [ ]:
X_train = train.drop(columns = 'SalePrice')
y_train = train['SalePrice']

In [ ]:
X_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [ ]:
print(X_train.shape)
print(y_train.shape)

(1460, 80)
(1460,)

In [ ]:
isnull_sum = X_train.isnull().sum()
isnull_sum

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
Length: 80, dtype: int64

In [ ]:
num_vars = X_train.select_dtypes(['int64','float64']).columns
miss_num_vars = [var for var in num_vars if isnull_sum[var]>0 ]

In [ ]:
num_vars2 = X_train.select_dtypes(['int64','float64']).columns
clean_num_vars = [var for var in num_vars2 if isnull_sum[var] == 0 ]
clean_num_vars

['Id',
 'MSSubClass',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [ ]:
num_vars3 = test.select_dtypes(['int64','float64']).columns
clean_num_vars2 = [var for var in num_vars3 if isnull_sum[var] == 0 ]
clean_num_vars2

In [ ]:
miss_num_vars

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [ ]:
cat_vars = X_train.select_dtypes(['O']).columns
miss_cat_vars = [var for var in cat_vars if isnull_sum[var]>0 ]
miss_cat_vars

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [ ]:
cat_vars2 = X_train.select_dtypes(['O']).columns
clean_cat_vars = [var for var in cat_vars2 if isnull_sum[var]==0 ]
clean_cat_vars

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'Functional',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

For now our task is to create a pipeline for different strategies of imputations.

In [ ]:
num_vars_mean = ['LotFrontage']
num_vars_meadian = [ 'MasVnrArea', 'GarageYrBlt']
cat_vars_mode = ['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu']
cat_vars_constant = ['GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [ ]:
num_vars_mean_imputer = Pipeline(steps = [('imputer', SimpleImputer(strategy='mean'))])
num_vars_median_imputer = Pipeline(steps = [('imputer', SimpleImputer(strategy='median'))])
num_vars_mode_imputer = Pipeline(steps = [('imputer', SimpleImputer(strategy='most_frequent'))])
num_vars_constant_imputer = Pipeline(steps = [('imputer', SimpleImputer(strategy='constant', fill_value='missing'))])

In [ ]:
preprocessor = ColumnTransformer([('mean_imputer' , num_vars_mean_imputer ,num_vars_mean ),
                   ('median_imputer' ,num_vars_median_imputer, num_vars_meadian ),
                   ('mode_imputer' ,num_vars_mode_imputer,cat_vars_mode  ),
                   ('constant_imputer',num_vars_constant_imputer,  cat_vars_constant)], remainder = 'passthrough')

In [ ]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('constant_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])

In [ ]:
preprocessor.fit(X_train , )

ColumnTransformer(remainder='passthrough',
                  transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('constant_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])

In [ ]:
preprocessor.transform

<bound method ColumnTransformer.transform of ColumnTransformer(remainder='passthrough',
                  transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('constant_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])>

In [ ]:
preprocessor.named_transformers_('mean_imputer').named_steps['imputer'].statistics_
#preprocessor.named_transformers_()

TypeError: ignored

In [ ]:
train['LotFrontage'].mean()

70.04995836802665

In [ ]:
preprocessor.named_transformers_('mode_imputer').named_steps['imputer'].statistics_

TypeError: ignored

In [ ]:
X_train_clean = preprocessor.transform(X_train)
X_test_clean = preprocessor.transform(test)

In [ ]:
X_train_clean

array([[65.0, 196.0, 2003.0, ..., 2008, 'WD', 'Normal'],
       [80.0, 0.0, 1976.0, ..., 2007, 'WD', 'Normal'],
       [68.0, 162.0, 2001.0, ..., 2008, 'WD', 'Normal'],
       ...,
       [66.0, 0.0, 1941.0, ..., 2010, 'WD', 'Normal'],
       [68.0, 0.0, 1950.0, ..., 2010, 'WD', 'Normal'],
       [75.0, 0.0, 1965.0, ..., 2008, 'WD', 'Normal']], dtype=object)

In [ ]:
X_test_clean

array([[80.0, 0.0, 1961.0, ..., 2010, 'WD', 'Normal'],
       [81.0, 108.0, 1958.0, ..., 2010, 'WD', 'Normal'],
       [74.0, 0.0, 1997.0, ..., 2010, 'WD', 'Normal'],
       ...,
       [160.0, 0.0, 1960.0, ..., 2006, 'WD', 'Abnorml'],
       [62.0, 0.0, 1980.0, ..., 2006, 'WD', 'Normal'],
       [74.0, 94.0, 1993.0, ..., 2006, 'WD', 'Normal']], dtype=object)

In [ ]:
preprocessor.transformers_

[('mean_imputer',
  Pipeline(steps=[('imputer', SimpleImputer())]),
  ['LotFrontage']),
 ('median_imputer',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))]),
  ['MasVnrArea', 'GarageYrBlt']),
 ('mode_imputer',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent'))]),
  ['Alley',
   'MasVnrType',
   'BsmtQual',
   'BsmtCond',
   'BsmtExposure',
   'BsmtFinType1',
   'BsmtFinType2',
   'Electrical',
   'FireplaceQu']),
 ('constant_imputer', Pipeline(steps=[('imputer',
                   SimpleImputer(fill_value='missing', strategy='constant'))]), ['GarageType',
   'GarageFinish',
   'GarageQual',
   'GarageCond',
   'PoolQC',
   'Fence',
   'MiscFeature']),
 ('remainder',
  'passthrough',
  [0,
   1,
   2,
   4,
   5,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   27,
   28,
   29,
   34,
   36,
   37,
   38,
   39,
   40,
   41,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   61,
   62,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   75,
   76,
   77,
   78,
   79])]

In [ ]:
X_train_clean_df = pd.DataFrame(X_train_clean, columns = num_vars_mean + num_vars_meadian + cat_vars_mode + cat_vars_constant + clean_num_vars + clean_cat_vars)

In [ ]:
X_train_clean_df.head(20)

,LotFrontage,MasVnrArea,GarageYrBlt,Alley,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,...,ExterCond,Foundation,Heating,HeatingQC,CentralAir,KitchenQual,Functional,PavedDrive,SaleType,SaleCondition
0,65.0,196.0,2003.0,Grvl,BrkFace,Gd,TA,No,GLQ,Unf,...,61,0,0,0,0,0,2,2008,WD,Normal
1,80.0,0.0,1976.0,Grvl,None,Gd,TA,Gd,ALQ,Unf,...,0,0,0,0,0,0,5,2007,WD,Normal
2,68.0,162.0,2001.0,Grvl,BrkFace,Gd,TA,Mn,GLQ,Unf,...,42,0,0,0,0,0,9,2008,WD,Normal
3,60.0,0.0,1998.0,Grvl,None,TA,Gd,No,ALQ,Unf,...,35,272,0,0,0,0,2,2006,WD,Abnorml
4,84.0,350.0,2000.0,Grvl,BrkFace,Gd,TA,Av,GLQ,Unf,...,84,0,0,0,0,0,12,2008,WD,Normal
5,85.0,0.0,1993.0,Grvl,None,Gd,TA,No,GLQ,Unf,...,30,0,320,0,0,700,10,2009,WD,Normal
6,75.0,186.0,2004.0,Grvl,Stone,Ex,TA,Av,GLQ,Unf,...,57,0,0,0,0,0,8,2007,WD,Normal
7,70.049958,240.0,1973.0,Grvl,Stone,Gd,TA,Mn,ALQ,BLQ,...,204,228,0,0,0,350,11,2009,WD,Normal
8,51.0,0.0,1931.0,Grvl,None,TA,TA,No,Unf,Unf,...,0,205,0,0,0,0,4,2008,WD,Abnorml
9,50.0,0.0,1939.0,Grvl,None,TA,TA,No,GLQ,Unf,...,4,0,0,0,0,0,1,2008,WD,Normal
10,70.0,0.0,1965.0,Grvl,None,TA,TA,No,Rec,Unf,...,0,0,0,0,0,0,2,2008,WD,Normal
11,85.0,286.0,2005.0,Grvl,Stone,Ex,TA,No,GLQ,Unf,...,21,0,0,0,0,0,7,2006,New,Partial
12,70.049958,0.0,1962.0,Grvl,None,TA,TA,No,ALQ,Unf,...,0,0,0,176,0,0,9,2008,WD,Normal
13,91.0,306.0,2006.0,Grvl,Stone,Gd,TA,Av,Unf,Unf,...,33,0,0,0,0,0,8,2007,New,Partial
14,70.049958,212.0,1960.0,Grvl,BrkFace,TA,TA,No,BLQ,Unf,...,213,176,0,0,0,0,5,2008,WD,Normal
15,51.0,0.0,1991.0,Grvl,None,TA,TA,No,Unf,Unf,...,112,0,0,0,0,0,7,2007,WD,Normal
16,70.049958,180.0,1970.0,Grvl,BrkFace,TA,TA,No,ALQ,Unf,...,0,0,0,0,0,700,3,2010,WD,Normal
17,72.0,0.0,1967.0,Grvl,None,TA,TA,No,Unf,Unf,...,0,0,0,0,0,500,10,2006,WD,Normal
18,66.0,0.0,2004.0,Grvl,None,TA,TA,No,GLQ,Unf,...,102,0,0,0,0,0,6,2008,WD,Normal
19,70.0,0.0,1958.0,Grvl,None,TA,TA,No,LwQ,Unf,...,0,0,0,0,0,0,5,2009,COD,Abnorml

## **For TEST DATA FRAME we have to do all this stuffs from the scratch**

In [ ]:
X_test_clean_df = pd.DataFrame(X_test_clean, columns = num_vars_mean + num_vars_meadian + cat_vars_mode + cat_vars_constant + clean_num_vars + clean_cat_vars)
X_test_clean_df.head(20)

,LotFrontage,MasVnrArea,GarageYrBlt,Alley,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,...,ExterCond,Foundation,Heating,HeatingQC,CentralAir,KitchenQual,Functional,PavedDrive,SaleType,SaleCondition
0,80.0,0.0,1961.0,Grvl,None,TA,TA,No,Rec,LwQ,...,0,0,0,120,0,0,6,2010,WD,Normal
1,81.0,108.0,1958.0,Grvl,BrkFace,TA,TA,No,ALQ,Unf,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,74.0,0.0,1997.0,Grvl,None,Gd,TA,No,GLQ,Unf,...,34,0,0,0,0,0,3,2010,WD,Normal
3,78.0,20.0,1998.0,Grvl,BrkFace,TA,TA,No,GLQ,Unf,...,36,0,0,0,0,0,6,2010,WD,Normal
4,43.0,0.0,1992.0,Grvl,None,Gd,TA,No,ALQ,Unf,...,82,0,0,144,0,0,1,2010,WD,Normal
5,75.0,0.0,1993.0,Grvl,None,Gd,TA,No,Unf,Unf,...,84,0,0,0,0,0,4,2010,WD,Normal
6,70.049958,0.0,1992.0,Grvl,None,Gd,TA,No,ALQ,Unf,...,21,0,0,0,0,500,3,2010,WD,Normal
7,63.0,0.0,1998.0,Grvl,None,Gd,TA,No,Unf,Unf,...,75,0,0,0,0,0,5,2010,WD,Normal
8,85.0,0.0,1990.0,Grvl,None,Gd,TA,Gd,GLQ,Unf,...,0,0,0,0,0,0,2,2010,WD,Normal
9,70.0,0.0,1970.0,Grvl,None,TA,TA,No,ALQ,Rec,...,0,0,0,0,0,0,4,2010,WD,Normal
10,26.0,0.0,1999.0,Grvl,None,Gd,TA,No,GLQ,BLQ,...,68,0,0,0,0,0,6,2010,WD,Normal
11,21.0,504.0,1971.0,Grvl,BrkFace,TA,TA,No,Rec,Unf,...,0,0,0,0,0,0,2,2010,COD,Normal
12,21.0,492.0,1997.0,Grvl,BrkFace,TA,TA,No,Rec,Unf,...,0,0,0,0,0,0,3,2010,WD,Normal
13,24.0,0.0,1975.0,Grvl,None,TA,TA,No,ALQ,Unf,...,0,0,0,0,0,0,6,2010,WD,Normal
14,24.0,0.0,1975.0,Grvl,None,Gd,TA,No,Unf,Unf,...,30,0,0,0,0,0,6,2010,WD,Normal
15,102.0,162.0,2009.0,Grvl,Stone,Ex,TA,No,Unf,Unf,...,133,0,0,0,0,0,1,2010,New,Partial
16,94.0,256.0,2009.0,Grvl,Stone,Gd,TA,No,Unf,Unf,...,35,0,0,0,0,0,6,2010,New,Partial
17,90.0,615.0,2005.0,Grvl,BrkFace,Ex,TA,No,GLQ,Unf,...,74,0,0,0,0,0,6,2010,WD,Normal
18,79.0,240.0,2005.0,Grvl,BrkFace,Ex,TA,No,GLQ,Unf,...,119,0,0,0,0,0,2,2010,WD,Normal
19,110.0,1095.0,2003.0,Grvl,BrkFace,Ex,TA,Gd,GLQ,Unf,...,150,0,0,0,0,0,6,2010,WD,Normal

In [ ]:
X_test_clean_df.isnull().sum().sum()

22